### ISSUE TITLE
Using `request` makes this only available in Node

### ISSUE THREAD

**Issue by treyhuffine** [alanshaw/embed-video#12]
We should use an AJAX library that works both in node and the browser.

http://andrewhfarmer.com/ajax-libraries/

**Comment by alanshaw** [comment]
I'm not sure what you mean when you say `request` works only in node. I believe it's browserify/webpack/other compatible. Is there another reason?

**Comment by treyhuffine** [comment]
It can transpile with the browserify and webpack. The issue is that when you the import/require `request` on the client, it then tries to import `tls`, `net`, and other packages that aren't available on the browser since they are only part of the Node API. While Webpack creates the link between these packages, it doesn't make native node packages available on a browser - you would still need to polyfill them (if even possible for the ones that `request` uses). My suggestion is that embed-video use a library where this isn't an issue.

**Comment by alanshaw** [comment]
Since the module is primarily aimed at use in the browser I think it would be best to use https://github.com/qubyte/fetch-ponyfill so that eventually we can remove the dependency (in browsers) when all browsers support the fetch API.

**Comment by treyhuffine** [comment]
Let me know if the update in the PR works

**Comment by terion-name** [comment]
yes, this script simply doesn't work in browser now, this update needed
