### ISSUE TITLE
IE11 CORS error fetching vimeo thumbnail image

### ISSUE THREAD

**Issue by stahlmanDesign** [alanshaw/embed-video#8]
Here's a strange one. On IE11, fetching the YouTube image works fine and returns an object `{err: null, thumbnail: {...}}`

But the exact same code requesting the thumbnail image from a vimeo video returns an error:
`SEC7118: XMLHttpRequest for http://vimeo.com/api/v2/video/200927594.json required Cross Origin Resource Sharing (CORS).`

This alternative code does work in IE11. It uses the jsonp API from Vimeo
http://jsfiddle.net/archatas/Tv7GZ/

I ended up using the npm module `fetch-jsonp` to fetch vimeo thumbs instead of embed-video. But you could patch your plugin using fetch-jsonp to get around this issue in IE11
```
import fetchJsonp from 'fetch-jsonp'
...
fetchJsonp('http://vimeo.com/api/v2/video/' + vimeoId + '.json')
.then((response)=> {
  return response.json()
}).then((json)=> {
  console.log('parsed json', json)
  let copiedState = Object.assign([],this.state.imageSources)
  copiedState[i] = json[0].thumbnail_small
  this.setState({imageSources: copiedState})
}).catch((ex)=> {
  console.log('parsing failed', ex)
})
```

**Comment by treyhuffine** [comment]
I'm looking into a similar issue right now. The problem is that `request` is used which is available in node but not the browser.

https://github.com/alanshaw/embed-video/issues
